# Generated by Django 4.2.3 on 2023-10-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_userprofile_is_super_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="is_super_user",),
        migrations.AlterField(
            model_name="userprofile",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
